### ISSUE TITLE
Can't locate object method "logger" via package "WebService::Mattermost::V4::Client"

### ISSUE THREAD

**Issue by bruberg** [n7st/WebService-Mattermost#19]
I've installed WebService::Mattermost in Docker, with most required packages installed from CPAN. I'm getting the following error:

`Can't locate object method "logger" via package "WebService::Mattermost::V4::Client" at /usr/local/lib/perl5/site_perl/5.32.0/WebService/Mattermost/V4/Client.pm line 133.`

WebService::Mattermost is version 0.23.
Mojolicious is version 8.70. 
I'll be happy to provide any other relevant version numbers.

Sample code:
```
#!/usr/bin/env perl
use strict;
use warnings;
use WebService::Mattermost::V4::Client;
my $bot = WebService::Mattermost::V4::Client->new({
    username   => 'user@domain',
    password   => 'Super_Sikrit',
    auth_token => 'Even_More_Sikrit',
    base_url   => 'https://mattermost.domain/api/v4/',
    debug      => 1,
});
```
Please advise.

**Comment by n7st** [comment]
Hi @bruberg,

Looks like I forgot to include the "logger" role in that class and it only shows up if you have `debug` set to `1`. I'll sort this now and let you know when the new version's on CPAN.

In the meantime here's a workaround:

```
#!/usr/bin/env perl
use strict;
use warnings;
use WebService::Mattermost::V4::Client;
my $bot = WebService::Mattermost::V4::Client->new({
    username   => 'user@domain',
    password   => 'Super_Sikrit',
    auth_token => 'Even_More_Sikrit',
    base_url   => 'https://mattermost.domain/api/v4/',
});
```

Thanks!

**Comment by bruberg** [comment]
Thanks for the quick response, but simply removing debug unfortunately isn't enough. I tried that, but forgot to add that info to the issue.

Without debug, I'm getting the following error:

`Mojo::Reactor::Poll: I/O watcher failed: Can't locate object method "logger" via package "WebService::Mattermost::V4::Client" at /usr/local/lib/perl5/site_perl/5.32.0/WebService/Mattermost/V4/Client.pm line 100.`

I don't know whether the suggested fix will also take care of this.

**Comment by n7st** [comment]
Yep, the fix that's currently being released will fix this issue too. The CPAN upload just completed and the new version (0.24) should be up soon.
